### ISSUE TITLE
Error when resolve_relation_values=True

### ISSUE THREAD

**Issue by thielem** [lolipopshock/notion-df#29]
Hey!
In contrast to #26 , I can see rollups an relations when resolve_relation_values =False. When I set `resolve_relation_values=True`, I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\m_thi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Beschreibung'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "a:\xxx\notion_fin_test.py", line 10, in <module>
    df = notion_df.download(page_url, resolve_relation_values=True)
  File "C:\Users\m_thi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\notion_df\agent.py", line 54, in wrapper
    out = func(client=client, *args, **kwargs)
  File "C:\Users\m_thi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\notion_df\agent.py", line 216, in download
    relation_df.notion_ids, relation_df[rel_title_col]
  File "C:\Users\m_thi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\m_thi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'Beschreibung'
```

**Comment by AlienCubeX** [comment]
Also when resolve_relation_values=False, no relation properties show up - only rollups are showing. When False, there is no error though

**Comment by lolipopshock** [comment]
Thanks! Will take a look later!
